duplicates:
  "Горные извилины (СПЧ) (Грозный)" : "Горные извилины (Грозный)"
  "Карате после (Карабулак)": "Карате После (Яндаре)"
  "Команда №17 (Вернисаж) (Дзержинск Нижегородская область)": "Команда №17 (Дзержинск Нижегородская область)"
  "Молекула Интеллекта (Тихвин)": "Молекулы Интеллекта (Тихвин)"
  "Ргуповцы (Город Нижний Новгород)": "РГУПовцы (Нижний Новгород)"
  "Техника Театр Кукол (Москва)": "Техника театр кукол (Калининград)"
  " (Саранск)": "Команда Абрамовой (Саранск)"
  "Ромашка Омск (Омск)": "Ромашка (Омск)"
  "Тузбубён (Москва)": "Тузбубен (Москва)"

ignore:
  - Вспомнить всё (Саров)

cities:
  "" : ""
